config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  # Defines the root path route ("/")
  # root "posts#index"
  
  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'shifts#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :shifts
  namespace :admin do 
    resources :users
  end 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user

    if @user.blank?
      self.public
    else
      self.private
    end
  end

  private

  def public
    # There arent public permissions in this version
  end

  def private
    case 
    when @user.has_role?(:admin)
      apply_admin_permissions
    when @user.has_role?(:scheduler)
      apply_scheduler_permissions
    when @user.has_role?(:employee)
      apply_employee_permissions
    end
  end
  
  def apply_admin_permissions
    can :manage, :all
  end

  def apply_scheduler_permissions
    can :manage, User
    cannot :manage, User, id: @user.id
    can :manage, Shift
    can :manage, Role, name: [:scheduler, :employee]
  end
  
  def apply_employee_permissions
    can :read, User, id: @user.id
    can :read, Shift, user: @user
    can :update, Shift, user: @user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user

  validates :start_time, :end_time, presence: true, overlap: { 
    message_title: "dates",
    message_content: "overlap with other shift" 
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  # Manage user roles
  rolify

  # Manage user permissions
  # This line allow us to use user.can? or user.cannot? for any user
  # while the default can? and cannot? methods only check against devise current_user
  delegate :can?, :cannot?, to: :ability 

  has_many :shifts

  validates :name, presence: true
  validates :employee_id, presence: true, if: :is_employee?

  def ability
    @ability ||= Ability.new(self)
  end

  def is_employee?
    has_role? :employee
  end

  def update_user_role(role_params)
    if role_params[:role].present? && can?(:manage, Role)
      add_role role_params[:role]
    end
  end

  def check_if_employee
    # We add this condition to block the users views from being accessed by a user (by typing the url)
    # This is because they actually have permissions to read themselves but we dont want them to access the admin view
    if is_employee?
      raise CanCan::AccessDenied, 'You are not authorized to access this page.'
    end 
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  before_action :set_roles, only: [:new, :create, :edit, :update]
  before_action :check_if_employee, only: [:index, :show]

  def index
  end

  def show
  end

  def new
  end

  def create
    if @user.save
      @user.update_user_role(role_params)

      redirect_to admin_users_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      @user.update_user_role(role_params)

      redirect_to admin_users_path, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "User was successfully deleted."
  end
  
  private

  def set_roles
    @roles = Role.accessible_by(current_user.ability)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :employee_id)
  end

  def role_params
    params.permit(:role)
  end

  def check_if_employee
    current_user.check_if_employee
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to '/', alert: exception.message }
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  load_and_authorize_resource

  before_action :set_users, only: [:new, :create, :edit, :update]

  def index
  end

  def show
  end

  def new
  end

  def create
    if @shift.save
      redirect_to shifts_path, notice: "Shift was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # CanCan makes :update an alias of :edit
    # But we shouldnt allow employees to edit shifts, only updating "acknowledged" field
    if can?(:edit, @shift) && current_user.is_employee?
      raise CanCan::AccessDenied, 'Employees cant edit shifts.'
    end 
  end

  def update
    if @shift.update(update_params)
      redirect_to shifts_path, notice: @flash_notice
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @shift.destroy
    redirect_to shifts_path, notice: "Shift was successfully deleted."
  end
  
  private

  def set_users
    @users = User.accessible_by(current_user.ability)
  end

  def shift_params
    params.require(:shift).permit(:user_id, :start_time, :end_time, :notes, :acknowledged)
  end

  def shift_employees_params
    params.require(:shift).permit(:acknowledged)
  end

  def update_params 
    # CanCan makes :update an alias of :edit
    # But we shouldnt allow employees to edit shifts, only updating "acknowledged" field
    if can?(:update, @shift) && current_user.is_employee?
      @flash_notice = "Shift was successfully acknowledged."
      shift_employees_params 
    else 
      @flash_notice = "Shift was successfully updated."
      shift_params 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-lg-8">
    <%= form_for(user, url: url, html: { class: 'shifts' }) do |f| %>
      <%= render "layouts/alerts" %>

      <% if user.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <%= user.errors.full_messages.to_sentence.capitalize %>.
        </div>
      <% end %>

      <div class="row">
        <div class="col-xs-12 col-lg-6">
          <label class="form-label">Role</label>
          <%= select_tag :role, options_for_select(@roles.map { |role| [role.name.capitalize, role.name] }, (user.roles[0]&.name || :employee)), class: "form-select" %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-lg-6">
          <label class="form-label">Name</label>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
        </div>

        <div class="col-xs-12 col-lg-6">
          <label class="form-label">Employee ID</label>
          <%= f.text_field :employee_id, class: 'form-control', placeholder: 'Enter Employee ID' %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-lg-4">
          <label class="form-label">Email</label>
          <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email' %>
        </div>

        <div class="col-xs-12 col-lg-4">
          <label class="form-label">Password</label>
          <% placeholder = @minimum_password_length ? "Enter password (#{@minimum_password_length} characters minimum)": 'Enter password' %>
          <%= f.password_field :password, class: 'form-control', placeholder: placeholder %>
        </div>
        <div class="col-xs-12 col-lg-4">
          <label class="form-label">Password Confirmation</label>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation' %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 text-center">
          <%= f.submit class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.employee_id %></td>
  <td class="table-actions">
    <%= link_to admin_user_path(user), class: "btn btn-success" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607ZM10.5 7.5v6m3-3h-6" />
      </svg>
    <% end %>

    <%= link_to edit_admin_user_path(user), class: "btn btn-primary" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
      </svg>
    <% end %>

    <%= button_to admin_user_path(user), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }, class: 'delete-btn' }, class: "btn btn-danger" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
      </svg>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for :title, "Edit User" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>Edit user</h1>
      </div>
      <div class="page-actions"></div>
    </div>
  </div>
  <%= render "form", user: @user, url: admin_user_path %>
</main>

<%= link_to sanitize("&larr; Back to users"), admin_users_path %>

app/views/admin/users/index.html.erb
<% content_for :title, "Users" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>Users</h1>
      </div>
      <div class="page-actions">
        <%= link_to new_admin_user_path, class: "btn btn-success d-flex align-items-center" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <span>
            New User
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <% if @users.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Employee ID</th>
          <th scope="col" class="table-actions"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  <% else %>
    <div class="row">
      <div class="col-xs-12">
        <div class="alert alert-primary" role="alert">
          No users found. Please create one to access this feature.
        </div>
      </div>
    </div>
  <% end %>
</main>

app/views/admin/users/new.html.erb
<% content_for :title, "New User" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>New user</h1>
      </div>
      <div class="page-actions"></div>
    </div>
  </div>
  <%= render "form", user: @user, url: admin_users_path %>
</main>

<%= link_to sanitize("&larr; Back to users"), admin_users_path %>

app/views/admin/users/show.html.erb
<% content_for :title, "User ##{@user.id}" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>User</h1>
      </div>
      <div class="page-actions">
        <%= link_to new_admin_user_path, class: "btn btn-success d-flex align-items-center" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <span>
            New Shift
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <td><b>Name</b></td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td><b>Email</b></td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td><b>Employee ID</b></td>
        <td><%= @user.employee_id %></td>
      </tr>
    </tbody>
  </table>
</main>

<%= link_to sanitize("&larr; Back to users"), admin_users_path %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="/">
        <%= image_tag "/logo.png", class: 'img-fluid logo' %>
      </a>
    </li>
    <% if can? :manage, User %>
      <li class="nav-item pages">
        <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
      </li>
    <% end %>
    <% if can? :read, Shift %>
      <li class="nav-item pages">
        <%= link_to 'Shifts', shifts_path, class: 'nav-link' %>
      </li>
    <% end %>
    <li class="nav-item pages">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "ShiftManager - #{content_for(:title)}" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body class="<%= current_user ? '' : 'text-center login' %>">
    <% if current_user %> 
      <%= render "layouts/header" %>
      <div class="container-fluid shiftmanager">
        <%= render "layouts/alerts" %>
        <% if user_signed_in? %>
          <h5 class="text-center">Welcome <%= current_user.name %></h5>
        <% end %> 
        <%= yield %>
      </div>
    <% else %>
      <!-- devise views -->
      <%= yield %>
    <% end %>
  
    <!-- Bootstrap javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- flatpickr javascript -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>
      flatpickr('.datepicker', { });
    </script>
  </body>
</html>

app/views/shifts/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-lg-8">
    <%= form_for(shift, html: { class: 'shifts' }) do |f| %>
      <%= render "layouts/alerts" %>

      <% if shift.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <%= shift.errors.full_messages.to_sentence.capitalize %>.
        </div>
      <% end %>

      <div class="row">
        <div class="col-xs-12 col-lg-6">
          <label class="form-label">User</label>
          <%= f.select :user_id, 
              options_for_select(@users.map { |user| ["#{user.name} (#{user.email})", user.id]}, shift&.user&.id), 
              { :include_blank => 'Select a user' },
              class: "form-select" %>
        </div>

        <div class="col-xs-12 col-lg-6">
          <div class="form-check">
            <%= f.check_box :acknowledged, { class: "form-check-input" } %>
            <label class="form-check-label form-label" for="flexCheckDefault">
              Acknowledged
            </label>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-lg-6">
          <label class="form-label">Start Time</label>
          <%= f.text_field :start_time, class: 'form-control bg-white datepicker', placeholder: 'Starts At', data: { 'date-format': 'Y-m-d H:i', 'enable-time': 'true' } %>
        </div>
        <div class="col-xs-12 col-lg-6">
          <label class="form-label">End Time</label>
          <%= f.text_field :end_time, class: 'form-control bg-white datepicker', placeholder: 'Ends At', data: { 'date-format': 'Y-m-d H:i', 'enable-time': 'true' } %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-lg-12">
          <label class="form-label">Notes</label>
          <%= f.text_area :notes, class: 'form-control', placeholder: 'Observations', rows: 5 %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 text-center">
          <%= f.submit class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shifts/_shift.html.erb
<tr>
  <td><%= shift.user.name %></td>
  <td class="text-center"><%= shift.start_time.strftime('%d/%m/%Y - %H:%M') %></td>
  <td class="text-center"><%= shift.end_time.strftime('%d/%m/%Y - %H:%M') %></td>
  <td class="table-actions">
    <% if can? :read, shift %>
      <%= link_to shift_path(shift), class: "btn btn-success" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607ZM10.5 7.5v6m3-3h-6" />
        </svg>
      <% end %>
    <% end %>

    <% if can? :edit, shift && current_user.is_employee? %>
      <% unless current_user.is_employee? %>
        <%= link_to edit_shift_path(shift), class: "btn btn-primary" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
          </svg>
        <% end %>
      <% end %>
    <% end %>

    <% if can? :delete, shift %>
      <%= button_to shift_path(shift), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }, class: 'delete-btn' }, class: "btn btn-danger" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
        </svg>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/shifts/edit.html.erb
<% content_for :title, "Edit Shift" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>Edit shift</h1>
      </div>
      <div class="page-actions"></div>
    </div>
  </div>
  <%= render "form", shift: @shift %>
</main>

<%= link_to sanitize("&larr; Back to shifts"), shifts_path %>

app/views/shifts/index.html.erb
<% content_for :title, "Shifts" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>Shifts</h1>
      </div>
      <div class="page-actions">
        <% if can? :create, Shift %>
          <%= link_to new_shift_path, class: "btn btn-success d-flex align-items-center" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
            <span>
              New Shift
            </span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <% if @shifts.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Employee</th>
          <th scope="col" class="text-center">Start At</th>
          <th scope="col" class="text-center">Ends At</th>
          <th scope="col" class="table-actions"></th>
        </tr>
      </thead>
      <tbody>
          <%= render @shifts %>
      </tbody>
    </table>
  <% else %>
    <div class="row">
      <div class="col-xs-12">
        <div class="alert alert-primary" role="alert">
          You dont have any shifts at the moment.
        </div>
      </div>
    </div>
  <% end %>
</main>

app/views/shifts/new.html.erb
<% content_for :title, "New Shift" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>New shift</h1>
      </div>
      <div class="page-actions"></div>
    </div>
  </div>
  <%= render "form", shift: @shift %>
</main>

<%= link_to sanitize("&larr; Back to shifts"), shifts_path %>

app/views/shifts/show.html.erb
<% content_for :title, "Shift ##{@shift.id}" %>

<main>
  <div class="header">
    <div class="row">
      <div class="page-title">
        <h1>Shift</h1>
      </div>
      <div class="page-actions">
        <% unless @shift.acknowledged %>
          <%= form_for(@shift, method: :patch) do |f| %>
            <%= f.hidden_field :acknowledged, value: true %>
            <%= button_tag type: :submit, class: "btn btn-success d-flex align-items-center" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
              </svg>
              <span>
                Acknowledge Shift
              </span>
            <% end %> 
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <td><b>Name</b></td>
        <td><%= @shift.user.name %></td>
      </tr>
      <tr>
        <td><b>Email</b></td>
        <td><%= @shift.user.email %></td>
      </tr>
      <tr>
        <td><b>Employee ID</b></td>
        <td><%= @shift.user.employee_id %></td>
      </tr>
      <tr>
        <td><b>Starts At</b></td>
        <td><%= @shift.start_time.strftime('%d/%m/%Y - %H:%M') %></td>
      </tr>
      <tr>
        <td><b>Ends At</b></td>
        <td><%= @shift.end_time.strftime('%d/%m/%Y - %H:%M') %></td>
      </tr>
      <tr>
        <td><b>Acknowledged</b></td>
        <td>
          <% if @shift.acknowledged %>
            <span class="badge text-bg-success">
              Acknowledged
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
              </svg>
            </span>
          <% else %>
            <span class="badge text-bg-secondary">
              Pending
            </span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><b>Notes</b></td>
        <td><%= @shift.notes %></td>
      </tr>
    </tbody>
  </table>
</main>

<%= link_to sanitize("&larr; Back to shifts"), shifts_path %>